name: Build Docker image

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Log in to container registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build & push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: ghcr.io/matrix-org/patience:latest
